apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    group: example
spec:
  selector:
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
spec:
  selector:
    matchExpressions:
      - { key: app, operator: In, values: [second-app, first-app] }
    # matchLabels:
    #   app: second-app
  replicas: 2
  template: 
    metadata:
      labels:
        app: second-app
    spec:
      containers:
        - name: second-app-container
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          image: michalsniezko/kub-first-app:2
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 3
            initialDelaySeconds: 5
          